name: 🚀 Build & Validate

on:
  repository_dispatch:
    types: [ libs-versions-updated ]
  pull_request:
    paths:
      - '**/*'
      - '!**/.github/workflows/**'

jobs:
  lint:
    name: 🔍 Lint & Code Style Check
    runs-on: ubicloud-standard-4
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v5

      - name: ✅ Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: 📜 Copy CI gradle.properties
        run: mkdir -p ~/.gradle && cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: 🏗️ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: ⚙️ Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: 🧼 Run Spotless Check
        run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache

  build:
    name: 🏗️ Build & Compile
    needs: lint  # Only runs if lint passes ✅
    runs-on: ubicloud-standard-4
    timeout-minutes: 45
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v5

      - name: 📜 Copy CI gradle.properties
        run: mkdir -p ~/.gradle && cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: 🏗️ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: ⚙️ Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: 🧹 Clean Project
        run: ./gradlew clean

      - name: 🔨 Build Project
        run: ./gradlew build
